[package]
name = "ariad-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
ariad-host = { path = "../ariad-host", version = "0.0.0" }
clap.workspace = true

[dev-dependencies]
ariad-core = { path = "../ariad-core", version = "0.0.0" }
hex.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2.workspace = true
tokio-util = { workspace = true, features = ["rt"] }
toml.workspace = true

[[bin]]
name = "ashift"
path = "src/main.rs"

[lints]
workspace = true
